# Версия синтаксиса docker-compose
version: '3.8'

# Описание наших сервисов (пока только один - база данных)
services:
  # Название нашего сервиса (может быть любым)
  db:
    # Используем официальный образ PostgreSQL версии 15
    image: postgres:15
    # Перезапускать контейнер автоматически, если он упал
    restart: always
    # Переменные окружения для настройки PostgreSQL
    environment:
      # Имя пользователя-суперпользователя
      POSTGRES_USER: exchange_admin
      # Пароль для этого пользователя
      POSTGRES_PASSWORD: team4
      # Название базы данных, которая будет создана при первом запуске
      POSTGRES_DB: exchange_platform_db
    # Пробрасываем порт из контейнера (5432) на наш компьютер (5433)
    # Это нужно, чтобы мы могли подключиться к БД с нашей машины.
    # Используем 5433, чтобы не конфликтовать с локально установленным PostgreSQL, если он есть.
    ports:
      - "5433:5432"
    # Создаем "том" (volume) для хранения данных.
    # Это гарантирует, что данные не пропадут при перезапуске контейнера.
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Описание томов, которые мы используем
volumes:
  postgres_data: